README.md

- lab solutions
- add curriculum
- add more explanations
- minor text edits

Update guide to chapter 5

---

README.md

- fix typos 
- update descriptions

[CHAPTER 5] Typos and Descriptions

---

README.md

📝 add default editor to ch4 setup

[CHAPTER 4] Default kubectl text editor

---

README.md

- add useful links
- add more annotations
- add more snippets
- add official guide docs
Closes #2

[CHAPTER 5] Update namespaces section for clarity

---

README.md

- update labs
- add more annotations
- add lab solutions
- format with prettier

[CHAPTER 7] Update labs

---

README.md

- add more annotations
- add revised labs
- add lab solutions
- refactor `watch` command to `kubectl --watch`

[CHAPTER 8] Update labs and annotations

---

README.md

- revise labs
- add lab solutions
- add more annotations

[CHAPTER 9] Update labs, lab solutions and annotations

---

README.md

- update docker installation
- update deployment annotations
- general corrections

[Cleanup] Edit annotations and tips

---

README.md

- minor fixes for previous chapters
- add ch14 troubleshooting draft

[CHAPTER 14] Add initial troubleshooting notes

---

README.md

- add new lab and solution for better ingress understanding

[CHAPTER 9] Update labs

---

README.md

- variables, configmaps, secrets
- pod lifecycle, update strategy
- k8s API

[CHAPTER 11] Add new labs and update annotations

---

README.md

These tasks cover ch2 docker and ch4-5 pods, and will improve student debugging skills 
- add task 1-5
- add lab 6.7

[TASKS] Add tasks 1-5 to improve debugging skills

---

README.md

- add task deployment
- add task service
- add task service ii

[TASKS] Add three new tasks

---

README.md

ckad bootcamp -> kubernetes bootcamp (ckad)

[TITLE] Update repo name and doc title

---

README.md

- reduce the hints
- add more lab annotations in favour of hints

[TASKS] Update Service II hints

---

README.md

- add task ingress
- add task network policy
- add task persistent volume
- add task configmap and secret
- add task probes

[TASKS] Add new tasks for ch9-ch12

---

README.md

- update requirements section
- update lab 12.1
- add lab 12.2
- add lab 12.3
- add task probes
- add task zero-downtime deployment

[TASKS] Add tasks and labs in ch12

---

README.md

- "ubuntu users" text is bold, drop bold text

[FIX] Drop bold text in requirements section

---

README.md

- add exam tips chapter
- add sections with divs for printing

[CHAPTER] Exam tips

---

README.md

- add tasks explanation to chapter learning outcomes

[CHAPTER] Update learning outcome

---

README.md

- fix typo in learning outcome

[TYPO] Update learning-outcome

---

README.md

- add ckad exam link in ch-learning-outcomes
- add command to list running containers in lab1.2

[FIX] Add link to ckad exam

---

README.md

- update windows next steps after docker install
- fix typo in basic docker commands

[UPDATE] Update windows requirements section

---

README.md

- update how to use repo
- update exam readiness guide

[EXAM] Update repo usage sections

---

README.md

Add a section to view all available tasks

[TASKS] Add tasks list in ch15

---

README.md

- Add new FAQs
- Refactor suitable sections to FAQ

[FAQ] Add new faq section 

---

README.md

[PREFACE] Update requirements text

---

CONTRIBUTING.md
README.md

[CONTRIBUTING] Add contributing.md

---

README.md

replace "proficiency with IaC" to "proficiency with kubernetes"

[LEARNING_OUTCOMES] Drop IaC reference

---

README.md

small fix to prevent confusion.

exposing webapp deployment creates webapp service, so querying it instead of nginx

---

README.md

- Make it clearer that a network policy will not work without a suitable network provider
- minor case edits

[CHAPTER-9] Add notes on network provider requirements

---

README.md

In response to _@AliMoeen in https://github.com/piouson/kubernetes-bootcamp/discussions/45_

[FAQ] Add faq for toc

---

README.md

- update minikube install to use latest k8s version
- k8s v1.24 issue now resolved
- fix ingress lab destroy command

📝 update minikube install steps
